# Site settings
title: Roman Fleischanderl
email: fleischanderl.roman@gmail.com
#url: https://rfle.github.io/
production_url : https://rfle.github.io/portfolio/
BASE_PATH : https://rfle.github.io/portfolio/
basurl: "portfolio"
description: "Portfolio von Roman Fleischanderl - Webdesign - Entwicklung"
keywords: "your keywords, separated by commas"
skills: "Webdesign - Entwicklung - E-Commerce"
meta_author: Fleischanderl Roman

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 293133 #80B3FF
  primary-rgb: "41,49,51" #"128,179,255"
  secondary: 293133  #FD6E8A
  secondary-dark: 6E9058 #A2122F

# Footer settings
footer:
  copyright: Roman Fleischanderl
  location: Wien, AT
  social: Soziale Netzwerke
  #credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/rfle

# Postal address (add as many lines as necessary)
address:
  - line: fleischanderl.roman@gmail.com


# Credits content
#credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
